FROM alpine:latest

EXPOSE 8080
RUN mkdir -p /opt
USER root

RUN yum -y update
RUN yum -y install java-11-openjdk-devel
RUN yum install nodejs
RUN npm install -g nodemon
RUN npm i mongoose
#RUN yum install -y mongodb-org

COPY dist/app.jar /opt/app.jar

#WORKDIR /home

CMD [ "sh", "-c", "java -jar /opt/app.jar" ]
