pipeline {
    agent { label 'aws-agent' }
    environment {
                AWS_ACCESS_KEY_ID = credentials('access-key')
                AWS_SECRET_ACCESS_KEY = credentials('secret-key')
                ARTIFACTORY_USER = credentials('jfrog-user')
                ARTIFACTORY_PASSWORD = credentials('jfrog-password')
                ARTIFACTORY_SERVER = credentials('jfrog-server')
    }
    stages {
        stage('Agent Initialization') {
            steps {
                sh '''
                sudo yum update -y
                sudo amazon-linux-extras install docker -y
                sudo systemctl enable docker
                sudo service docker start
                
                cd /home/ec2-user/workspace/prod-pipeline/

                wget https://releases.hashicorp.com/terraform/1.2.8/terraform_1.2.8_linux_amd64.zip
                unzip terraform_1.2.8_linux_amd64.zip
                rm terraform_1.2.8_linux_amd64.zip
                sudo mv terraform /usr/bin
                
                REPO="/home/ec2-user/workspace/prod-pipeline/da-final-project"
                if [ -d "$REPO" ]
                then
                    cd $REPO
                    cd ..
                    rm -rf da-final-project
                fi
                cd /home/ec2-user/workspace/prod-pipeline/
                git clone https://github.com/nkaGL/da-final-project.git
                cd da-final-project
                git checkout main
                git pull
                '''
            }
        }
        stage('Merge to Prod') {
            steps {
                sh '''
                cd /home/ec2-user/workspace/prod-pipeline/da-final-project
                git merge origin/dev
                '''
            }
        }
        stage('Build') {
            steps {
                sh '''
                cd /home/ec2-user/workspace/prod-pipeline/da-final-project
                ./gradlew build
               '''
            }
        }
        stage('Dockerization') {
            steps {
               sh'''
                cd /home/ec2-user/workspace/prod-pipeline/da-final-project
                
                now=$(date +"%d%m%Y")
                BUILD_NAME=$now"-jenkins-build-prod"
                sudo docker login -u$ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD $ARTIFACTORY_SERVER
                sudo docker build -t $BUILD_NAME .
                IMAGE_ID=$(sudo docker images | grep -i $BUILD_NAME | awk '{ print $3 }')
                sudo docker tag $IMAGE_ID $ARTIFACTORY_SERVER/ninagl-docker-prod-local/dev/webapp:latest
                sudo docker push $ARTIFACTORY_SERVER/ninagl-docker-prod-local/dev/webapp:latest
                '''
            }
        }
        stage('Deployment') {
            steps {
                sh '''
                cd /home/ec2-user/workspace/prod-pipeline/da-final-project/.terraform-prod
                terraform init
                terraform apply -auto-approve
                '''
                
                // prod-webapp_public_ip=$(terraform output -raw prod-webapp_public_ip)
                // ssh -oStrictHostKeyChecking=no $prod-webapp_public_ip uptime
                // ssh $prod-webapp_public_ip
                // sudo docker pull mongo
                // sudo docker run -it --rm -d --name mongo -p 27017:27017 mongo
                // sudo docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD $ARTIFACTORY_SERVER
                // sudo docker run -it --rm -d --name webapp -p 8080:8080 --net host $ARTIFACTORY_SERVER/project-docker-local/dev/webapp:latest
                // exit
                // '''
            }
        }
        stage('Smoke Tests') {
            steps {
              sh '''
              echo "smoke tests"
              '''
              //curl $prod-webapp_public_ip:8080 | grep "DevOps"
                
            }
        }
        stage('Documentation generation') {
            steps {
               sh 'echo Doxygen'
            }
        }
    }
}